### PR TITLE
task2

### PR DESCRIPTION
**Pull request by Sasha567898**

### CODE REVIEW

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
no actions

**Comment by Sasha567898** [comment]
Додав

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
still can't find any actions or artifacts.

**Comment by Sasha567898** [comment]
corrected it

сб, 16 лист. 2024 р. о 19:14 andrii-s-spitzer-lpnu-ua <
***@***.***> пише:

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Pull request merged**
